import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export const LANGUAGES = [
  { code: 'en', name: 'English',  native: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi',    native: 'हिन्दी',   flag: '🇮🇳' },
  { code: 'te', name: 'Telugu',   native: 'తెలుగు',   flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil',    native: 'தமிழ்',    flag: '🇮🇳' },
  { code: 'zh', name: 'Chinese',  native: '中文',      flag: '🇨🇳' },
  { code: 'fr', name: 'French',   native: 'Français', flag: '🇫🇷' },
];

export const TRANSLATIONS = {
  en: {
    // Navbar
    explore: 'Explore',
    dashboard: 'Dashboard',
    signIn: 'Sign in',
    getStarted: 'Get started',
    signOut: 'Sign out',
    language: 'Language',
    // Landing
    badge: 'AI-powered learning · 500+ topics',
    heroTitle1: 'Learn anything,',
    heroTitle2: 'master everything',
    heroDesc: 'InsightMint transforms YouTube videos into complete learning experiences — with AI summaries, flashcards, quizzes, and personalized roadmaps.',
    searchPlaceholder: 'Search any topic — Python, Machine Learning, System Design...',
    tryLabel: 'Try:',
    exploreBtn: 'Explore',
    topicsCovered: 'Topics covered',
    videosCurated: 'Videos curated',
    learnersDaily: 'Learners daily',
    satisfaction: 'Satisfaction rate',
    featuresTitle: 'Everything you need to learn faster',
    featuresSubtitle: 'Powered by AI, curated for humans',
    trendingTitle: 'Trending Topics',
    viewAll: 'View all',
    learners: 'learners',
    ctaTitle: 'Start learning today',
    ctaSubtitle: 'Free forever. No credit card required.',
    createAccount: 'Create free account',
    browseTopics: 'Browse topics',
    footerText: 'Built for curious minds.',
    // Features
    feat1Title: 'Curated Videos',
    feat1Desc: 'Top educational YouTube videos for any topic you want to master',
    feat2Title: 'AI Study Notes',
    feat2Desc: 'Auto-generated summaries, flashcards, and quizzes from video content',
    feat3Title: 'Learning Roadmap',
    feat3Desc: 'Personalized step-by-step paths to achieve mastery',
    feat4Title: 'AI Tutor Chat',
    feat4Desc: 'Ask questions and get instant, contextual answers about any topic',
    // Explore
    exploreTitle: 'Explore',
    exploreAny: 'any topic',
    exploreSubtitle: 'Find the best educational videos and generate AI study materials',
    searchBtn: 'Search',
    popularTopics: 'Popular topics',
    findingVideos: 'Finding the best videos for',
    resultsFor: 'Results for',
    videosFound: 'educational videos found',
    // Video page
    backToResults: 'Back to results',
    studyNotes: 'Study Notes',
    flashcardsTab: 'Flashcards',
    quizTab: 'Quiz',
    roadmapTab: 'Roadmap',
    aiTutorTab: 'AI Tutor',
    generatingNotes: 'Generating AI study notes...',
    aiSummary: 'AI Summary',
    keyTakeaways: 'Key Takeaways',
    downloadPDF: 'Download PDF',
    // Flashcards
    flashcardsTitle: 'Flashcards',
    question: 'Question',
    answer: 'Answer',
    clickReveal: 'Click to reveal answer',
    needReview: 'Need review',
    gotIt: 'Got it!',
    total: 'total',
    generatingFlashcards: 'Generating flashcards...',
    // Quiz
    quizTitle: 'Knowledge Quiz',
    quizComplete: 'Quiz Complete!',
    youScored: 'You scored',
    retakeQuiz: 'Retake Quiz',
    nextQuestion: 'Next Question',
    seeResults: 'See Results',
    explanation: 'Explanation:',
    generatingQuiz: 'Generating quiz...',
    // Roadmap
    roadmapTitle: 'Learning Roadmap',
    roadmapSubtitle: 'Your path to mastering',
    overallProgress: 'Overall progress',
    skillsToLearn: 'Skills to learn',
    resources: 'Resources',
    markComplete: 'Mark as complete',
    completed: '✓ Completed',
    generatingRoadmap: 'Building your learning roadmap...',
    // Chat
    chatTitle: 'AI Tutor',
    chatPlaceholder: 'Ask about',
    online: 'online',
    // Auth
    welcomeBack: 'Welcome back',
    startLearning: 'Start learning today',
    signInSubtitle: 'Sign in to continue your learning journey',
    signUpSubtitle: 'Create your free account in seconds',
    fullName: 'Full name',
    yourName: 'Your name',
    emailAddress: 'Email address',
    password: 'Password',
    processing: 'Processing...',
    noAccount: "Don't have an account?",
    signUpFree: 'Sign up free',
    haveAccount: 'Already have an account?',
    // Dashboard
    recentlyWatched: 'Recently watched',
    findMore: 'Find more →',
    quickActions: 'Quick actions',
    exploreNewTopic: 'Explore new topic',
    exploreNewDesc: 'Search for videos & get AI notes',
    continueLearning: 'Continue learning',
    videosWatched: 'Videos watched',
    topicsExplored: 'Topics explored',
    studyStreak: 'Study streak',
    quizzesTaken: 'Quizzes taken',
    days: 'days',
    noVideos: 'No videos watched yet',
  },

  hi: {
    explore: 'खोजें',
    dashboard: 'डैशबोर्ड',
    signIn: 'साइन इन',
    getStarted: 'शुरू करें',
    signOut: 'साइन आउट',
    language: 'भाषा',
    badge: 'AI-संचालित शिक्षा · 500+ विषय',
    heroTitle1: 'कुछ भी सीखें,',
    heroTitle2: 'सब कुछ माहिर करें',
    heroDesc: 'InsightMint YouTube वीडियो को पूर्ण शिक्षण अनुभव में बदलता है — AI सारांश, फ्लैशकार्ड, क्विज़ और व्यक्तिगत रोडमैप के साथ।',
    searchPlaceholder: 'कोई भी विषय खोजें — Python, Machine Learning, System Design...',
    tryLabel: 'आज़माएं:',
    exploreBtn: 'खोजें',
    topicsCovered: 'विषय शामिल',
    videosCurated: 'वीडियो संकलित',
    learnersDaily: 'दैनिक शिक्षार्थी',
    satisfaction: 'संतुष्टि दर',
    featuresTitle: 'तेज़ सीखने के लिए सब कुछ',
    featuresSubtitle: 'AI द्वारा संचालित, मनुष्यों के लिए',
    trendingTitle: 'ट्रेंडिंग विषय',
    viewAll: 'सभी देखें',
    learners: 'शिक्षार्थी',
    ctaTitle: 'आज ही सीखना शुरू करें',
    ctaSubtitle: 'हमेशा के लिए मुफ़्त। कोई क्रेडिट कार्ड नहीं।',
    createAccount: 'मुफ़्त अकाउंट बनाएं',
    browseTopics: 'विषय ब्राउज़ करें',
    footerText: 'जिज्ञासु मनों के लिए बनाया गया।',
    feat1Title: 'क्यूरेटेड वीडियो',
    feat1Desc: 'किसी भी विषय के लिए शीर्ष शैक्षिक YouTube वीडियो',
    feat2Title: 'AI स्टडी नोट्स',
    feat2Desc: 'वीडियो से स्वचालित सारांश, फ्लैशकार्ड और क्विज़',
    feat3Title: 'लर्निंग रोडमैप',
    feat3Desc: 'महारत हासिल करने के लिए व्यक्तिगत चरण-दर-चरण पथ',
    feat4Title: 'AI ट्यूटर चैट',
    feat4Desc: 'किसी भी विषय पर तत्काल, संदर्भित उत्तर पाएं',
    exploreTitle: 'खोजें',
    exploreAny: 'कोई भी विषय',
    exploreSubtitle: 'सर्वश्रेष्ठ शैक्षिक वीडियो खोजें और AI सामग्री बनाएं',
    searchBtn: 'खोजें',
    popularTopics: 'लोकप्रिय विषय',
    findingVideos: 'के लिए सर्वश्रेष्ठ वीडियो खोज रहे हैं',
    resultsFor: 'के लिए परिणाम',
    videosFound: 'शैक्षिक वीडियो मिले',
    backToResults: 'परिणामों पर वापस',
    studyNotes: 'स्टडी नोट्स',
    flashcardsTab: 'फ्लैशकार्ड',
    quizTab: 'क्विज़',
    roadmapTab: 'रोडमैप',
    aiTutorTab: 'AI ट्यूटर',
    generatingNotes: 'AI स्टडी नोट्स बना रहे हैं...',
    aiSummary: 'AI सारांश',
    keyTakeaways: 'मुख्य बिंदु',
    downloadPDF: 'PDF डाउनलोड करें',
    flashcardsTitle: 'फ्लैशकार्ड',
    question: 'प्रश्न',
    answer: 'उत्तर',
    clickReveal: 'उत्तर देखने के लिए क्लिक करें',
    needReview: 'समीक्षा चाहिए',
    gotIt: 'समझ गया!',
    total: 'कुल',
    generatingFlashcards: 'फ्लैशकार्ड बना रहे हैं...',
    quizTitle: 'ज्ञान क्विज़',
    quizComplete: 'क्विज़ पूर्ण!',
    youScored: 'आपका स्कोर',
    retakeQuiz: 'फिर से क्विज़ दें',
    nextQuestion: 'अगला प्रश्न',
    seeResults: 'परिणाम देखें',
    explanation: 'व्याख्या:',
    generatingQuiz: 'क्विज़ बना रहे हैं...',
    roadmapTitle: 'लर्निंग रोडमैप',
    roadmapSubtitle: 'महारत हासिल करने का आपका पथ',
    overallProgress: 'कुल प्रगति',
    skillsToLearn: 'सीखने के कौशल',
    resources: 'संसाधन',
    markComplete: 'पूर्ण चिह्नित करें',
    completed: '✓ पूर्ण',
    generatingRoadmap: 'आपका लर्निंग रोडमैप बना रहे हैं...',
    chatTitle: 'AI ट्यूटर',
    chatPlaceholder: 'के बारे में पूछें',
    online: 'ऑनलाइन',
    welcomeBack: 'वापस स्वागत है',
    startLearning: 'आज सीखना शुरू करें',
    signInSubtitle: 'अपनी शिक्षा यात्रा जारी रखें',
    signUpSubtitle: 'सेकंड में मुफ़्त अकाउंट बनाएं',
    fullName: 'पूरा नाम',
    yourName: 'आपका नाम',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    processing: 'प्रसंस्करण...',
    noAccount: 'अकाउंट नहीं है?',
    signUpFree: 'मुफ़्त साइन अप करें',
    haveAccount: 'पहले से अकाउंट है?',
    recentlyWatched: 'हाल ही में देखे गए',
    findMore: 'और खोजें →',
    quickActions: 'त्वरित क्रियाएं',
    exploreNewTopic: 'नया विषय खोजें',
    exploreNewDesc: 'वीडियो खोजें और AI नोट्स पाएं',
    continueLearning: 'सीखना जारी रखें',
    videosWatched: 'वीडियो देखे',
    topicsExplored: 'विषय खोजे',
    studyStreak: 'स्टडी स्ट्रीक',
    quizzesTaken: 'क्विज़ दिए',
    days: 'दिन',
    noVideos: 'अभी तक कोई वीडियो नहीं देखा',
  },

  te: {
    explore: 'అన్వేషించు',
    dashboard: 'డాష్‌బోర్డ్',
    signIn: 'సైన్ ఇన్',
    getStarted: 'ప్రారంభించండి',
    signOut: 'సైన్ అవుట్',
    language: 'భాష',
    badge: 'AI-శక్తితో నేర్చుకోండి · 500+ అంశాలు',
    heroTitle1: 'ఏదైనా నేర్చుకోండి,',
    heroTitle2: 'అన్నింటిలో నిపుణులు అవ్వండి',
    heroDesc: 'InsightMint YouTube వీడియోలను పూర్తి అభ్యాస అనుభవాలుగా మారుస్తుంది — AI సారాంశాలు, ఫ్లాష్‌కార్డ్‌లు, క్విజ్‌లు మరియు వ్యక్తిగత రోడ్‌మ్యాప్‌లతో.',
    searchPlaceholder: 'ఏదైనా అంశం వెతకండి — Python, Machine Learning, System Design...',
    tryLabel: 'ప్రయత్నించండి:',
    exploreBtn: 'అన్వేషించు',
    topicsCovered: 'అంశాలు కవర్ చేయబడ్డాయి',
    videosCurated: 'వీడియోలు సేకరించబడ్డాయి',
    learnersDaily: 'రోజువారీ విద్యార్థులు',
    satisfaction: 'సంతృప్తి రేటు',
    featuresTitle: 'వేగంగా నేర్చుకోవడానికి అన్నీ',
    featuresSubtitle: 'AI ద్వారా శక్తివంతమైంది, మనుషుల కోసం',
    trendingTitle: 'ట్రెండింగ్ అంశాలు',
    viewAll: 'అన్నీ చూడండి',
    learners: 'విద్యార్థులు',
    ctaTitle: 'ఈరోజే నేర్చుకోవడం ప్రారంభించండి',
    ctaSubtitle: 'ఎప్పటికీ ఉచితం. క్రెడిట్ కార్డు అవసరం లేదు.',
    createAccount: 'ఉచిత ఖాతా సృష్టించండి',
    browseTopics: 'అంశాలు బ్రౌజ్ చేయండి',
    footerText: 'ఉత్సుకులైన మనసుల కోసం నిర్మించబడింది.',
    feat1Title: 'క్యూరేటెడ్ వీడియోలు',
    feat1Desc: 'మీరు నేర్చుకోవాలనుకునే ఏ అంశానికైనా అగ్ర విద్యా YouTube వీడియోలు',
    feat2Title: 'AI స్టడీ నోట్స్',
    feat2Desc: 'వీడియో కంటెంట్ నుండి స్వయంచాలక సారాంశాలు, ఫ్లాష్‌కార్డ్‌లు మరియు క్విజ్‌లు',
    feat3Title: 'లెర్నింగ్ రోడ్‌మ్యాప్',
    feat3Desc: 'నైపుణ్యం సాధించడానికి వ్యక్తిగత దశల వారీ మార్గాలు',
    feat4Title: 'AI ట్యూటర్ చాట్',
    feat4Desc: 'ఏ అంశంపైనైనా తక్షణ, సందర్భోచిత సమాధానాలు పొందండి',
    exploreTitle: 'అన్వేషించు',
    exploreAny: 'ఏదైనా అంశం',
    exploreSubtitle: 'అత్యుత్తమ విద్యా వీడియోలు కనుగొనండి మరియు AI అధ్యయన సామగ్రి రూపొందించండి',
    searchBtn: 'వెతకండి',
    popularTopics: 'జనాదరణ పొందిన అంశాలు',
    findingVideos: 'కోసం అత్యుత్తమ వీడియోలు కనుగొంటున్నాము',
    resultsFor: 'కోసం ఫలితాలు',
    videosFound: 'విద్యా వీడియోలు కనుగొనబడ్డాయి',
    backToResults: 'ఫలితాలకు తిరిగి',
    studyNotes: 'స్టడీ నోట్స్',
    flashcardsTab: 'ఫ్లాష్‌కార్డ్‌లు',
    quizTab: 'క్విజ్',
    roadmapTab: 'రోడ్‌మ్యాప్',
    aiTutorTab: 'AI ట్యూటర్',
    generatingNotes: 'AI స్టడీ నోట్స్ రూపొందిస్తున్నాము...',
    aiSummary: 'AI సారాంశం',
    keyTakeaways: 'ముఖ్యమైన విషయాలు',
    downloadPDF: 'PDF డౌన్‌లోడ్ చేయండి',
    flashcardsTitle: 'ఫ్లాష్‌కార్డ్‌లు',
    question: 'ప్రశ్న',
    answer: 'సమాధానం',
    clickReveal: 'సమాధానం చూడటానికి క్లిక్ చేయండి',
    needReview: 'సమీక్ష అవసరం',
    gotIt: 'అర్థమైంది!',
    total: 'మొత్తం',
    generatingFlashcards: 'ఫ్లాష్‌కార్డ్‌లు రూపొందిస్తున్నాము...',
    quizTitle: 'జ్ఞాన క్విజ్',
    quizComplete: 'క్విజ్ పూర్తయింది!',
    youScored: 'మీరు స్కోర్ చేశారు',
    retakeQuiz: 'క్విజ్ మళ్లీ తీసుకోండి',
    nextQuestion: 'తదుపరి ప్రశ్న',
    seeResults: 'ఫలితాలు చూడండి',
    explanation: 'వివరణ:',
    generatingQuiz: 'క్విజ్ రూపొందిస్తున్నాము...',
    roadmapTitle: 'లెర్నింగ్ రోడ్‌మ్యాప్',
    roadmapSubtitle: 'నైపుణ్యం సాధించడానికి మీ మార్గం',
    overallProgress: 'మొత్తం పురోగతి',
    skillsToLearn: 'నేర్చుకోవాల్సిన నైపుణ్యాలు',
    resources: 'వనరులు',
    markComplete: 'పూర్తయినట్లు గుర్తించు',
    completed: '✓ పూర్తయింది',
    generatingRoadmap: 'మీ లెర్నింగ్ రోడ్‌మ్యాప్ నిర్మిస్తున్నాము...',
    chatTitle: 'AI ట్యూటర్',
    chatPlaceholder: 'గురించి అడగండి',
    online: 'ఆన్‌లైన్',
    welcomeBack: 'తిరిగి స్వాగతం',
    startLearning: 'ఈరోజే నేర్చుకోవడం ప్రారంభించండి',
    signInSubtitle: 'మీ అభ్యాస ప్రయాణాన్ని కొనసాగించండి',
    signUpSubtitle: 'సెకన్లలో ఉచిత ఖాతా సృష్టించండి',
    fullName: 'పూర్తి పేరు',
    yourName: 'మీ పేరు',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    processing: 'ప్రాసెస్ అవుతోంది...',
    noAccount: 'ఖాతా లేదా?',
    signUpFree: 'ఉచితంగా సైన్ అప్ చేయండి',
    haveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    recentlyWatched: 'ఇటీవల చూసినవి',
    findMore: 'మరిన్ని కనుగొనండి →',
    quickActions: 'త్వరిత చర్యలు',
    exploreNewTopic: 'కొత్త అంశం అన్వేషించు',
    exploreNewDesc: 'వీడియోలు వెతకండి మరియు AI నోట్స్ పొందండి',
    continueLearning: 'నేర్చుకోవడం కొనసాగించు',
    videosWatched: 'వీడియోలు చూశారు',
    topicsExplored: 'అంశాలు అన్వేషించారు',
    studyStreak: 'స్టడీ స్ట్రీక్',
    quizzesTaken: 'క్విజ్‌లు తీసుకున్నారు',
    days: 'రోజులు',
    noVideos: 'ఇంకా వీడియోలు చూడలేదు',
  },

  ta: {
    explore: 'ஆராயுங்கள்',
    dashboard: 'டாஷ்போர்டு',
    signIn: 'உள்நுழை',
    getStarted: 'தொடங்குங்கள்',
    signOut: 'வெளியேறு',
    language: 'மொழி',
    badge: 'AI-இயங்கும் கற்றல் · 500+ தலைப்புகள்',
    heroTitle1: 'எதையும் கற்றுக்கொள்ளுங்கள்,',
    heroTitle2: 'அனைத்திலும் தேர்ச்சி பெறுங்கள்',
    heroDesc: 'InsightMint YouTube வீடியோக்களை முழுமையான கற்றல் அனுபவங்களாக மாற்றுகிறது — AI சுருக்கங்கள், ஃபிளாஷ்கார்டுகள், வினாடி வினாக்கள் மற்றும் தனிப்பயன் வழிமாப்புகளுடன்.',
    searchPlaceholder: 'எந்த தலைப்பையும் தேடுங்கள் — Python, Machine Learning, System Design...',
    tryLabel: 'முயற்சிக்கவும்:',
    exploreBtn: 'ஆராயுங்கள்',
    topicsCovered: 'தலைப்புகள் உள்ளடக்கப்பட்டன',
    videosCurated: 'வீடியோக்கள் தொகுக்கப்பட்டன',
    learnersDaily: 'தினசரி கற்பவர்கள்',
    satisfaction: 'திருப்தி விகிதம்',
    featuresTitle: 'வேகமாக கற்க தேவையான அனைத்தும்',
    featuresSubtitle: 'AI ஆல் இயங்கும், மனிதர்களுக்காக',
    trendingTitle: 'பிரபலமான தலைப்புகள்',
    viewAll: 'அனைத்தும் காண்க',
    learners: 'கற்பவர்கள்',
    ctaTitle: 'இன்றே கற்றலை தொடங்குங்கள்',
    ctaSubtitle: 'எப்போதும் இலவசம். கிரெடிட் கார்டு தேவையில்லை.',
    createAccount: 'இலவச கணக்கை உருவாக்கு',
    browseTopics: 'தலைப்புகளை உலாவுங்கள்',
    footerText: 'ஆர்வமுள்ள மனங்களுக்காக உருவாக்கப்பட்டது.',
    feat1Title: 'தொகுக்கப்பட்ட வீடியோக்கள்',
    feat1Desc: 'நீங்கள் கற்க விரும்பும் எந்த தலைப்பிற்கும் சிறந்த YouTube வீடியோக்கள்',
    feat2Title: 'AI படிப்பு குறிப்புகள்',
    feat2Desc: 'வீடியோ உள்ளடக்கத்திலிருந்து தானாக உருவாக்கப்பட்ட சுருக்கங்கள் மற்றும் வினாடி வினாக்கள்',
    feat3Title: 'கற்றல் வழிமாப்பு',
    feat3Desc: 'தேர்ச்சி பெற தனிப்பயன் படிப்படியான பாதைகள்',
    feat4Title: 'AI ஆசிரியர் அரட்டை',
    feat4Desc: 'எந்த தலைப்பிலும் உடனடி, சூழல் சார்ந்த பதில்கள் பெறுங்கள்',
    exploreTitle: 'ஆராயுங்கள்',
    exploreAny: 'எந்த தலைப்பும்',
    exploreSubtitle: 'சிறந்த கல்வி வீடியோக்களை கண்டறிந்து AI பொருட்களை உருவாக்குங்கள்',
    searchBtn: 'தேடு',
    popularTopics: 'பிரபலமான தலைப்புகள்',
    findingVideos: 'க்கான சிறந்த வீடியோக்களை கண்டறிகிறோம்',
    resultsFor: 'க்கான முடிவுகள்',
    videosFound: 'கல்வி வீடியோக்கள் கண்டறியப்பட்டன',
    backToResults: 'முடிவுகளுக்கு திரும்பு',
    studyNotes: 'படிப்பு குறிப்புகள்',
    flashcardsTab: 'ஃபிளாஷ்கார்டுகள்',
    quizTab: 'வினாடி வினா',
    roadmapTab: 'வழிமாப்பு',
    aiTutorTab: 'AI ஆசிரியர்',
    generatingNotes: 'AI படிப்பு குறிப்புகளை உருவாக்குகிறோம்...',
    aiSummary: 'AI சுருக்கம்',
    keyTakeaways: 'முக்கிய கருத்துக்கள்',
    downloadPDF: 'PDF பதிவிறக்கம்',
    flashcardsTitle: 'ஃபிளாஷ்கார்டுகள்',
    question: 'கேள்வி',
    answer: 'பதில்',
    clickReveal: 'பதிலை காண கிளிக் செய்யுங்கள்',
    needReview: 'மதிப்பாய்வு தேவை',
    gotIt: 'புரிந்தது!',
    total: 'மொத்தம்',
    generatingFlashcards: 'ஃபிளாஷ்கார்டுகளை உருவாக்குகிறோம்...',
    quizTitle: 'அறிவு வினாடி வினா',
    quizComplete: 'வினாடி வினா முடிந்தது!',
    youScored: 'நீங்கள் பெற்றீர்கள்',
    retakeQuiz: 'மீண்டும் வினாடி வினா',
    nextQuestion: 'அடுத்த கேள்வி',
    seeResults: 'முடிவுகளை காண்க',
    explanation: 'விளக்கம்:',
    generatingQuiz: 'வினாடி வினா உருவாக்குகிறோம்...',
    roadmapTitle: 'கற்றல் வழிமாப்பு',
    roadmapSubtitle: 'தேர்ச்சி பெற உங்கள் பாதை',
    overallProgress: 'ஒட்டுமொத்த முன்னேற்றம்',
    skillsToLearn: 'கற்க வேண்டிய திறன்கள்',
    resources: 'வளங்கள்',
    markComplete: 'முடிந்தது என குறி',
    completed: '✓ முடிந்தது',
    generatingRoadmap: 'உங்கள் கற்றல் வழிமாப்பை உருவாக்குகிறோம்...',
    chatTitle: 'AI ஆசிரியர்',
    chatPlaceholder: 'பற்றி கேளுங்கள்',
    online: 'நேரலை',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    startLearning: 'இன்றே கற்றலை தொடங்குங்கள்',
    signInSubtitle: 'உங்கள் கற்றல் பயணத்தை தொடருங்கள்',
    signUpSubtitle: 'நொடியில் இலவச கணக்கை உருவாக்குங்கள்',
    fullName: 'முழு பெயர்',
    yourName: 'உங்கள் பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    processing: 'செயலாக்குகிறோம்...',
    noAccount: 'கணக்கு இல்லையா?',
    signUpFree: 'இலவசமாக பதிவு செய்யுங்கள்',
    haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    recentlyWatched: 'சமீபத்தில் பார்த்தவை',
    findMore: 'மேலும் கண்டறி →',
    quickActions: 'விரைவு செயல்கள்',
    exploreNewTopic: 'புதிய தலைப்பை ஆராயுங்கள்',
    exploreNewDesc: 'வீடியோக்களை தேடி AI குறிப்புகளை பெறுங்கள்',
    continueLearning: 'கற்றலை தொடருங்கள்',
    videosWatched: 'வீடியோக்கள் பார்த்தன',
    topicsExplored: 'தலைப்புகள் ஆராயப்பட்டன',
    studyStreak: 'படிப்பு தொடர்ச்சி',
    quizzesTaken: 'வினாடி வினாக்கள் எடுத்தன',
    days: 'நாட்கள்',
    noVideos: 'இன்னும் வீடியோக்கள் பார்க்கவில்லை',
  },

  zh: {
    explore: '探索',
    dashboard: '仪表盘',
    signIn: '登录',
    getStarted: '开始使用',
    signOut: '退出',
    language: '语言',
    badge: 'AI驱动学习 · 500+ 主题',
    heroTitle1: '学习任何知识，',
    heroTitle2: '掌握一切技能',
    heroDesc: 'InsightMint将YouTube视频转化为完整的学习体验——包含AI摘要、闪卡、测验和个性化学习路线图。',
    searchPlaceholder: '搜索任何主题 — Python、机器学习、系统设计...',
    tryLabel: '试试:',
    exploreBtn: '探索',
    topicsCovered: '涵盖主题',
    videosCurated: '精选视频',
    learnersDaily: '每日学习者',
    satisfaction: '满意度',
    featuresTitle: '快速学习所需的一切',
    featuresSubtitle: 'AI驱动，专为人类设计',
    trendingTitle: '热门主题',
    viewAll: '查看全部',
    learners: '学习者',
    ctaTitle: '今天开始学习',
    ctaSubtitle: '永远免费。无需信用卡。',
    createAccount: '创建免费账户',
    browseTopics: '浏览主题',
    footerText: '为好奇的心灵而建。',
    feat1Title: '精选视频',
    feat1Desc: '任何主题的顶级教育YouTube视频',
    feat2Title: 'AI学习笔记',
    feat2Desc: '从视频内容自动生成摘要、闪卡和测验',
    feat3Title: '学习路线图',
    feat3Desc: '实现精通的个性化逐步路径',
    feat4Title: 'AI辅导聊天',
    feat4Desc: '获取任何主题的即时、上下文相关答案',
    exploreTitle: '探索',
    exploreAny: '任何主题',
    exploreSubtitle: '找到最好的教育视频并生成AI学习材料',
    searchBtn: '搜索',
    popularTopics: '热门主题',
    findingVideos: '正在为以下内容寻找最佳视频',
    resultsFor: '的搜索结果',
    videosFound: '个教育视频',
    backToResults: '返回结果',
    studyNotes: '学习笔记',
    flashcardsTab: '闪卡',
    quizTab: '测验',
    roadmapTab: '路线图',
    aiTutorTab: 'AI辅导',
    generatingNotes: '正在生成AI学习笔记...',
    aiSummary: 'AI摘要',
    keyTakeaways: '关键要点',
    downloadPDF: '下载PDF',
    flashcardsTitle: '闪卡',
    question: '问题',
    answer: '答案',
    clickReveal: '点击查看答案',
    needReview: '需要复习',
    gotIt: '明白了！',
    total: '共',
    generatingFlashcards: '正在生成闪卡...',
    quizTitle: '知识测验',
    quizComplete: '测验完成！',
    youScored: '你的得分',
    retakeQuiz: '重新测验',
    nextQuestion: '下一题',
    seeResults: '查看结果',
    explanation: '解释：',
    generatingQuiz: '正在生成测验...',
    roadmapTitle: '学习路线图',
    roadmapSubtitle: '您掌握的路径',
    overallProgress: '总体进度',
    skillsToLearn: '要学习的技能',
    resources: '资源',
    markComplete: '标记为完成',
    completed: '✓ 已完成',
    generatingRoadmap: '正在构建您的学习路线图...',
    chatTitle: 'AI辅导老师',
    chatPlaceholder: '询问关于',
    online: '在线',
    welcomeBack: '欢迎回来',
    startLearning: '今天开始学习',
    signInSubtitle: '继续您的学习之旅',
    signUpSubtitle: '几秒钟内创建免费账户',
    fullName: '全名',
    yourName: '您的名字',
    emailAddress: '电子邮件地址',
    password: '密码',
    processing: '处理中...',
    noAccount: '没有账户？',
    signUpFree: '免费注册',
    haveAccount: '已有账户？',
    recentlyWatched: '最近观看',
    findMore: '查找更多 →',
    quickActions: '快速操作',
    exploreNewTopic: '探索新主题',
    exploreNewDesc: '搜索视频并获取AI笔记',
    continueLearning: '继续学习',
    videosWatched: '已观看视频',
    topicsExplored: '已探索主题',
    studyStreak: '学习连续天数',
    quizzesTaken: '已完成测验',
    days: '天',
    noVideos: '尚未观看任何视频',
  },

  fr: {
    explore: 'Explorer',
    dashboard: 'Tableau de bord',
    signIn: 'Se connecter',
    getStarted: 'Commencer',
    signOut: 'Se déconnecter',
    language: 'Langue',
    badge: 'Apprentissage alimenté par IA · 500+ sujets',
    heroTitle1: 'Apprenez tout,',
    heroTitle2: 'maîtrisez tout',
    heroDesc: "InsightMint transforme les vidéos YouTube en expériences d'apprentissage complètes — avec des résumés IA, des flashcards, des quiz et des feuilles de route personnalisées.",
    searchPlaceholder: 'Rechercher un sujet — Python, Machine Learning, Conception système...',
    tryLabel: 'Essayez:',
    exploreBtn: 'Explorer',
    topicsCovered: 'Sujets couverts',
    videosCurated: 'Vidéos sélectionnées',
    learnersDaily: 'Apprenants par jour',
    satisfaction: 'Taux de satisfaction',
    featuresTitle: 'Tout ce dont vous avez besoin pour apprendre plus vite',
    featuresSubtitle: 'Propulsé par IA, conçu pour les humains',
    trendingTitle: 'Sujets tendance',
    viewAll: 'Voir tout',
    learners: 'apprenants',
    ctaTitle: "Commencez à apprendre aujourd'hui",
    ctaSubtitle: 'Gratuit pour toujours. Aucune carte de crédit requise.',
    createAccount: 'Créer un compte gratuit',
    browseTopics: 'Parcourir les sujets',
    footerText: 'Construit pour les esprits curieux.',
    feat1Title: 'Vidéos sélectionnées',
    feat1Desc: 'Les meilleures vidéos YouTube éducatives pour tout sujet',
    feat2Title: 'Notes IA',
    feat2Desc: 'Résumés, flashcards et quiz générés automatiquement',
    feat3Title: 'Feuille de route',
    feat3Desc: 'Parcours personnalisés étape par étape vers la maîtrise',
    feat4Title: 'Tuteur IA',
    feat4Desc: 'Obtenez des réponses instantanées sur tout sujet',
    exploreTitle: 'Explorer',
    exploreAny: 'tout sujet',
    exploreSubtitle: 'Trouvez les meilleures vidéos éducatives et générez du matériel IA',
    searchBtn: 'Rechercher',
    popularTopics: 'Sujets populaires',
    findingVideos: 'Recherche des meilleures vidéos pour',
    resultsFor: 'Résultats pour',
    videosFound: 'vidéos éducatives trouvées',
    backToResults: 'Retour aux résultats',
    studyNotes: 'Notes de cours',
    flashcardsTab: 'Flashcards',
    quizTab: 'Quiz',
    roadmapTab: 'Feuille de route',
    aiTutorTab: 'Tuteur IA',
    generatingNotes: 'Génération des notes IA...',
    aiSummary: 'Résumé IA',
    keyTakeaways: 'Points clés',
    downloadPDF: 'Télécharger PDF',
    flashcardsTitle: 'Flashcards',
    question: 'Question',
    answer: 'Réponse',
    clickReveal: 'Cliquez pour révéler la réponse',
    needReview: 'À revoir',
    gotIt: 'Compris !',
    total: 'total',
    generatingFlashcards: 'Génération des flashcards...',
    quizTitle: 'Quiz de connaissances',
    quizComplete: 'Quiz terminé !',
    youScored: 'Votre score',
    retakeQuiz: 'Reprendre le quiz',
    nextQuestion: 'Question suivante',
    seeResults: 'Voir les résultats',
    explanation: 'Explication :',
    generatingQuiz: 'Génération du quiz...',
    roadmapTitle: "Feuille de route d'apprentissage",
    roadmapSubtitle: 'Votre chemin vers la maîtrise de',
    overallProgress: 'Progression globale',
    skillsToLearn: 'Compétences à acquérir',
    resources: 'Ressources',
    markComplete: 'Marquer comme terminé',
    completed: '✓ Terminé',
    generatingRoadmap: 'Construction de votre feuille de route...',
    chatTitle: 'Tuteur IA',
    chatPlaceholder: 'Posez une question sur',
    online: 'en ligne',
    welcomeBack: 'Bon retour',
    startLearning: "Commencez à apprendre aujourd'hui",
    signInSubtitle: "Continuez votre parcours d'apprentissage",
    signUpSubtitle: 'Créez votre compte gratuit en quelques secondes',
    fullName: 'Nom complet',
    yourName: 'Votre nom',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    processing: 'Traitement...',
    noAccount: 'Pas de compte ?',
    signUpFree: "S'inscrire gratuitement",
    haveAccount: 'Déjà un compte ?',
    recentlyWatched: 'Récemment regardé',
    findMore: 'Trouver plus →',
    quickActions: 'Actions rapides',
    exploreNewTopic: 'Explorer un nouveau sujet',
    exploreNewDesc: 'Recherchez des vidéos et obtenez des notes IA',
    continueLearning: "Continuer l'apprentissage",
    videosWatched: 'Vidéos regardées',
    topicsExplored: 'Sujets explorés',
    studyStreak: "Série d'études",
    quizzesTaken: 'Quiz effectués',
    days: 'jours',
    noVideos: "Aucune vidéo regardée pour l'instant",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('insightmint_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('insightmint_language', language);
  }, [language]);

  const currentLang = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];
  const t = TRANSLATIONS[language] || TRANSLATIONS.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currentLang, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
};